name: Upload JAR to Azure Blob Storage

on:
  push:
    branches:
      - main

jobs:
  upload-jar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 16

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Build and Package with Maven
      run: mvn clean package

    - name: Append Date and Time to JAR Filename
      id: append_datetime
      run: echo "::set-output name=filename::azureapps-0.0.1-SNAPSHOT-$(date +'%Y%m%d%H%M%S').jar"

    - name: echo_everything
      id: echoing
      run: echo ${{ steps.append_datetime.outputs.filename }}  "ENV SEC echo ${{ env.AZURE_STORAGE_ACCOUNT  }} rep SEC  echo ${{ secrets.AZURE_STORAGE_ACCOUNT  }} "

    - name: Upload JAR to Azure Blob Storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.33.0
        inlineScript: |
          az storage blob upload --account-name "${{ secrets.AZURE_STORAGE_ACCOUNT }}" --account-key "${{ secrets.AZURE_STORAGE_ACCESS_KEY }}" --container-name az204container --type block --name ${{ steps.append_datetime.outputs.filename }} --type block --source ./target/azureapps-0.0.1-SNAPSHOT.jar --content-type "application/java-archive"
